on:
  workflow_dispatch:
  push:
    branches:
      - master

name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_UI }}
        run: |
          npm ci
          npm run build -w pkg/common
          npm run deploy -w pkg/ui
