on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,6,12,18 * * *" # Every 6 hours

name: Update leaderboard
jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Generate leaderboard
        run: |
          npm ci
          npm run build
          npm run generate
      - name: Push to master
        run: |
          git config --global user.name "sij1nk"
          git config --global user.email "gergo.rajnavolgyi@gmail.com"
          git add .
          git commit -m "Update"
          git push --set-upstream origin master
